logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:postgresql://localhost:5432/Latif_APP
    password: 1234
    username: postgres
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show-sql: true
  mail:
    host: smtp.gmail.com
    host_address: host_address
    username: username
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:8081/oauth/check_token
    client_id: client_id
    client_password: client_password
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Latif APP Documentation API
    version: v1
  contact:
    name: highcoder
    url: https://www.highcoder.com
    email: support@highcoder.com

