package com.commerce.backend.helper;

import lombok.Data;

@Data
public class FieldsNames {
    public static final String name = "name";
    public static final String name_ar = "الاسم";
    public static final String code = "Code";
    public static final String code_ar = "الكود";
    public static final String city = "City";
    public static final String city_ar = "المدينه";
    public static final String desc = "Description";
    public static final String desc_ar = "الوصف";
    public static final String short_desc = "Short Description";
    public static final String short_desc_ar = "الوصف المختصر";
    public static final String price = "Price";
    public static final String price_ar = "السعر";
    public static final String active = "Active";
    public static final String active_ar = "نشط";
    public static final String weaned = "weaned";
    public static final String weaned_ar = "مفطوم";
    public static final String bread = "Bread";
    public static final String bread_ar = "التربيه";
    public static final String training = "Training";
    public static final String training_ar = "مدرب";
    public static final String type = "Type";
    public static final String type_ar = "النوع";
    public static final String id = "Id";
    public static final String id_ar = "الرقم التسلسلى";
    public static final String longitude = "Longitude";
    public static final String longitude_ar = "خط الطول";
    public static final String latitude = "Latitude";
    public static final String latitude_ar = "خط العرض";
    public static final String createdAt = "Created At";
    public static final String createdAt_ar = "تاريخ الانشاء";
    public static final String updatedAt = "Updated At";
    public static final String updatedAt_ar = "تاريخ التعديل";
    public static final String externalLink = "External Link";
    public static final String externalLink_ar = "لينك خارجى";
    public static final String image = "Image";
    public static final String image_ar = "الصور";
    public static final String createdBy = "Created By";
    public static final String createdBy_ar = "تم الانشاء بواسطة";
    public static final String barkingProblem = "Barking Problem";
    public static final String barkingProblem_ar = "مشكلة النباح";
    public static final String food = "Food";
    public static final String food_ar = "الطعام";
    public static final String diseasesOrDisabilities = "Diseases or Disabilities";
    public static final String diseasesOrDisabilities_ar = "مرض او اعاقه";
    public static final String diseasesOrDisabilitiesDesc = "Diseases Disabilities Description";
    public static final String diseasesOrDisabilitiesDesc_ar = "وصف المرض او الاعاقه";
    public static final String Neutering = "Neutering";
    public static final String Neutering_ar = "التعقيم";
    public static final String PlayWithKids = "Play With Kids";
    public static final String PlayWithKids_ar = "اللعب مع الاطفال";
    public static final String Passport = "Passport";
    public static final String Passport_ar = "جواز السفر";
    public static final String VaccinationCertificate = "Vaccination Certificate ";
    public static final String VaccinationCertificate_ar = "شهادة تطعيم";
    public static final String Stock = "Stock";
    public static final String Stock_ar = "المخزون";
    public static final String AllowAtHome = "Delivery At Home";
    public static final String AllowAtHome_ar = "داخل المنزل";
    public static final String used = "used";
    public static final String used_ar = "مستعمل";
    public static final String Category = "Category";
    public static final String Category_ar = "الفئه";
    public static final String selling_type = "Ad Type";
    public static final String selling_type_ar = "نوع الإعلان";
    public static final String driver_method = "Driver Method";
    public static final String driver_method_ar = "طريقة التوصيل";
    public static final String catType = "category name";
    public static final String catType_ar = "اسم الفئة";
}
